AWSTemplateFormatVersion: "2010-09-09"

Description: >
  CloudFormation For S3 Bucket Creation.

Parameters:
  BucketNameParameter:
    Type: String

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameParameter
